name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: self-hosted
    environment: MONGO_URI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Print Env Secret
        run: echo "${{ secrets.PROD }}" > ./backend/.env

      - name: Stop PM2 processes
        run: pm2 stop all || true

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: yarn install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Run Backend Tests
        working-directory: ./backend
        run: yarn test || npm test

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          sudo rm -rf build/
          yarn run build

      - name: Restart PM2 processes
        run: pm2 restart all
